Import Dependencies

In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Import Data

In [41]:
data = pd.read_csv(r'D:\Downloads\Swarm_Behaviour.csv\Swarm_Behaviour.csv')

In [42]:
data.head()

x1      y1  xVel1  yVel1   xA1   yA1  xS1  yS1   xC1   yC1  ...  \
0   562.05   -0.62 -10.70  -4.33  0.00  0.00  0.0  0.0  0.00  0.00  ...   
1   175.66  -57.09   2.31  -2.67  0.00  0.00  0.0  0.0  0.00  0.00  ...   
2   200.16 -320.07   4.01  -6.37  0.00  0.00  0.0  0.0  0.18 -0.26  ...   
3   316.99 -906.84   0.85   9.17 -0.17  1.03  0.0  0.0  0.00  0.00  ...   
4  1277.68  908.54  -2.02   8.23 -1.00  1.00  0.0  0.0  0.00  0.00  ...   

   yVel200  xA200  yA200  xS200  yS200  xC200  yC200  nAC200  nS200  \
0   -15.15   0.00   0.00   0.00   0.00   0.00    0.0      28      0   
1    -3.48   0.00   0.00   0.00   0.00   0.00    0.0       4      0   
2    -9.38   0.00   0.00   0.00   0.00  -0.11   -0.3      15      1   
3    10.39  -0.26   1.01   0.00   0.00   0.00    0.0      16      0   
4    13.91  -1.00   0.00   3.21  15.67   0.00    0.0      12      0   

   Swarm_Behaviour  
0              0.0  
1              0.0  
2              0.0  
3              0.0  
4              0.0  

[5 rows x 2401 columns]

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23309 entries, 0 to 23308
Columns: 2401 entries, x1 to Swarm_Behaviour
dtypes: float64(2001), int64(400)
memory usage: 427.0 MB


In [44]:
for i in data.columns:
    if (data[i].isnull().sum()!=0):
        print(i)

In [45]:
def iqr(column , dataset = data):
    q1 = dataset[column].quantile(0.25)
    q3 = dataset[column].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - (1.5 * iqr)
    upper = q3 + (1.5 * iqr)
    return lower , upper

In [46]:
data.replace([-np.inf , np.inf] , np.nan  , inplace = True)

In [47]:
category = data.select_dtypes(exclude = ['int' , 'float']).columns

In [48]:
data.dropna(inplace=True)

No Null Values have been found 

In [29]:
for i in data.columns:
    lower , upper = iqr(i)
    l = len(data[(data[i]<=lower) | (data[i]>=upper)])
    if ((l/len(data)*100) > 20):
        data[i] = data[i][(data[i]>=lower) & (data[i]<=upper)]
        

KeyboardInterrupt: 

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23309 entries, 0 to 23308
Columns: 2401 entries, x1 to Swarm_Behaviour
dtypes: float64(2001), int64(400)
memory usage: 427.0 MB


In [50]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression

In [51]:
knn = KNeighborsClassifier()

In [52]:
gauss = GaussianNB()

In [53]:
lr = LogisticRegression()

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
x = data.drop(['Swarm_Behaviour'] , axis = 1)
y = data['Swarm_Behaviour']

In [56]:
x_train , x_test , y_train , y_Test = train_test_split(x , y , test_size = 0.25 , random_state = 42)

In [57]:
knn.fit(x_train , y_train)

KNeighborsClassifier()

In [58]:
gauss.fit(x_train , y_train)

GaussianNB()

In [59]:
lr.fit(x_train , y_train)

C:\Users\Aniruth\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [60]:
from sklearn.metrics import confusion_matrix as cfm

In [61]:
cfm(knn.predict(x_test) , y_Test)

array([[3479,  323],
       [ 340, 1686]], dtype=int64)

In [62]:
cfm(lr.predict(x_test) , y_Test)

array([[3534,  307],
       [ 285, 1702]], dtype=int64)

In [63]:
cfm(gauss.predict(x_test) , y_Test)

array([[ 688,  101],
       [3131, 1908]], dtype=int64)

In [64]:
from sklearn.metrics import precision_score

In [66]:
print("KNN : " , precision_score(knn.predict(x_test) , y_Test))
print("Logistic Regression : " , precision_score(lr.predict(x_test) , y_Test))
print("Naive Bayes : " , precision_score(gauss.predict(x_test) , y_Test))

KNN :  0.839223494275759
Logistic Regression :  0.8471876555500248
Naive Bayes :  0.9497262319561971


We can see that naive bayes is the best performing model